### ISSUE TITLE
A project with this name already exists in your workspace.

### ISSUE THREAD

**Issue by hemmeter** [joeferraro/MavensMate-SublimeText#213]
I am on the latest version of ST3 (build 3047) and mavensmate (0.35.1).

Upon creating a MavensMate project from a cloned repo, I get the error "A project with this name already exists in your workspace."

My steps...
1) Clone repo from BitBucket to my local FS. The folder is within the MM workspace
2) Open folder in Sublime 3
3) Right click on top of folder structure --> create MM project
4) Fill in username/pwd+token
5) Click Create Project
6) I get the error "A project with this name already exists in your workspace."

**Comment by AlwaysThinkin** [comment]
I was hitting the same issue still on OS X 10.8.5 in Sublime 3 (Build 3065) with MM 0.38.6 and applied @wes1278's symlink approach to solve. For those who read this in the future, on OS X the equivalent symlink command reverses the order of source and origin like so:
`ln -s /Users/myuser/Dropbox/git/projectX/src /Users/myuser/Dropbox/mm_workspace/projectX/src`

**Comment by jacobraccuia** [comment]
Deleting the trailing / at the end of the workspace path actually fixed it for me.

I had already been using git locally on my machine so these are the steps I took.

1.  Drag project into Sublime.
2.  Set mm_workspace to "/users/projectname" ( no trailing / !!!!!)
3. Right click project and create new MM project.
4. Fill in credentials.

I tested by modifying a class, which it then compiled.  When I ran a git status, it showed the file as being modified.

**Comment by joeferraro** [comment]
Just fyi guys, I know this has been a long-standing issue and the reason it hasn't been addressed in this project is because the entire core has been rewritten (https://github.com/joeferraro/MavensMate) and the new import project functionality addresses this UX, making it a lot more stable. more to come in the coming days, but just a heads up.

**Comment by msreekm** [comment]
Mac OSX - deleing the trailing / from mm_workspace path fixed it for me.

**Comment by textual** [comment]
just now encountering this issue, no trailing '/' in mm_workspace

**Comment by thajcak** [comment]
I just encountered this issue and fixed my changing my pattern.

Cloned repo from GitHub directly into MM Workspace.
Dragged project folder into SublimeText.
Tried to create project via right click menu. Received error.

Tried with project folder elsewhere on my system (moved it to ~).
Worked and noticed that it copied the project into my working directory.

To me, this looks like it might be an issue trying to move the project into the workspace if the project already exists in the workspace.

**Comment by yahirah** [comment]
Same problem as @thajcak  described, still persisting.
I cloned repo into the folder, that is defined as mm_workspace. I dragged it to the sublime and clicked to create new project. After filling in credentials, it returns "A project already exists in workspace". When trying to be clever and temporary remove the project - "There is no src folder". Trailing "/" doesn't make any difference.
